[phases.build]
nixpkgs = ["git"]

[phases.setup]
cmds = ["composer install --no-dev", "php artisan key:generate"]

[phases.install]
cmds = ["php artisan migrate --force", "php artisan db:seed --force"]

[start]
cmd = "php artisan serve --host=0.0.0.0 --port=$PORT"
