[build]
builder = "nixpacks"

[deploy]
startCommand = "php artisan serve --host=0.0.0.0 --port=$PORT"

[environments.variables]
APP_ENV = "production"
APP_DEBUG = "false"
LOG_LEVEL = "error"
DB_CONNECTION = "pgsql"
DB_HOST = "${{RAILWAY_TCP_PROXY_DEFAULT_HOST}}"
DB_PORT = "${{RAILWAY_TCP_PROXY_DEFAULT_PORT}}"
DB_DATABASE = "${{RAILWAY_POSTGRES_DB}}"
DB_USERNAME = "${{RAILWAY_POSTGRES_USER}}"
DB_PASSWORD = "${{RAILWAY_POSTGRES_PASSWORD}}"
